### ISSUE TITLE
TODO after Guake 3.0.0 release

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#1059]
Here is the status of the port of Guake to Python3, Gtk3 and Vte 2.91:

- [ ] FIX all #TODO PORT sections (Things to fix after the port)
- [ ] fix tab bar buttons sometimes losing their text (eg after adding 3+ new tabs from the context
  menu, hovering them restores the text) (I think this is a problem with the deprecated widgets
  which are still in use)
- [x] update the glade files (remove deprecated objects)

**Comment by gsemet** [comment]
not reproduced
