### ISSUE TITLE
Guake 3 Roadmap

### ISSUE THREAD

**Issue by Stibbons** [Guake/guake#872]
Here is a task list and Roadmap for the Guake 3 release

# Version
- jump directly from guake version 0.8.x to 3.0.0. 
- keep semver versioning

# Goals
- rewrite the core guake engine to more modular and more extensible
- plugin architecture
- port to gtk3, dconf, latest version of VTE
- dark theming (UI like sublime)

# Roadmap
## Guake 3.0 - "Proper Basis"

- [x] ~~**Rewrite the Build System for pip**: #873. even though Guake will still have hard dependency with system-level libraries such as libkeybinder, we need to switch to a clean pip compatible installation procedure. Drop all the makefile, autopen. I would like to put some build scripts to help bootstrapping their dev environment.~~
- [x] **move gettext Translation after all rewriten**: to keep the old translation we will reconstruct all Guake first THEN move back the `po` directory and update the translations, hoping gettext will be able to match translations
- [x] ~~**stricter code styling**: `validate` and `fiximports` will enforce more Pylint and pep8 checks. Stricter code style is not bad. use `_` to separate private/publicly available members in each class~~
- [ ] **no more global.py**
- [x] **Proper unit test integration**: #874

**Components**
- [x] **GuakeTerminal**: ported to gtk3 and new version of vte. add methods: search, save. Of course unit test
- [x] **GuakeTerminalPage**: replaces guakeTerminalBox. Allow to split the terminal horizontally and vertically. Provide accessor for visual position (`getTerminalByPos(0, 1)` to get terminal on first line, second column, `iterAllTerminals`` as an iterator all all terminals, `getCurrentTerminal`, `focusTerminalByPos(1, 0)` to focus second raw first column, `focusTerminalByShift(1,0)` to focus the terminal on the next row, `splitHorizontally`, `splitVertically`, `unplitHorizontally(deleteRight=True)`, `unsplitVertically(deleteBellow=True)`, and so on)
- [x] **GuakeTerminalTab**: merge all the `*_tab` functions from `Guake` class and the `GuakeNotebook` class. `Guake` class is too huge, lets apply the One Responsibility Principle. API Should be as simple as `addTab`, `splitCurTabVertically`, `unsplitCurTabVertically`. No more internal api hack
- [x] **GuakeWindow**: handle the placement of the Guake Window. Only that. Do exposes the tabs/page/terminal directly (using clean accessors), not by using proxy. #879
- [ ] **GuakeBinder**: proposal to bind events from keyboard/setting change to actions
- [x] **dconfhandler**: port gconfhandler to dconf
- [x] **dbus**: should be easy to port to gtk3
- [ ] **paletes.py**: port to a set of yams file => follow up #1053
- [ ] **Startup Script**: systemd scripts?
- [x] **Screen position computation**: rewrite the whole code, it is buggy, finding where to place the window is too complex, error prone, when fixing a bug another one appears. I do not see how to unit test it, since it depends on how gtk will position the window. Integration tests? => follow up #1054
- [ ] **Command line interface**: port CLI to guake3 branch

**Preferences** => follow up #1055
- [ ] **Rewrite preference window**. Too bloaty, difficult to modify and adapt. Find a more elegant disposition
- [ ] **Setting preference exposure**: too many files to modify when adding a setting, let's find a way to tell which setting gooes to which panel

**Plugin System** => #1052
- [ ] **Register/Unregister mechanism**: find a way for user to easily find and install new plugin. Probably like Sublime Text's Package Control. It a JSON file stores on github, user refresh periodicaly and are updated of new available packages on merge. Probably on https://github.come/Guake/plugins/plugins.xml
- [ ] **Python Event system** : Plugin will be able to react in python to some event:
- [ ] **2 Person review** : for plugin to be available to user, at least 2 person need code review
- [ ] **onion deployment**: plugins to be deployed using canary-like deployment. Users are packed into n different layers ("stable/unstable/cutting-edge" for instance) so they test plugins in advance

**Comment by mouseratti** [comment]
Should new code be in a separated branch? or I can make pull requests to master? IMHO, it should be a new fresh branch or, maybe, new repo.

**Comment by Stibbons** [comment]
Follow up => Plugin #1052
